-- SaraDrive `users` table — web/mobile JWT auth (register/login/me).
--
-- OWNERSHIP: the database schema is owned by `schema.sql` in the umbrella repo
-- (Sarastya-project), which the Postgres container applies on first init. This file is
-- the canonical definition of the `users` table; Phase 2B appends it to that schema.sql
-- (after now_text() is defined). The .NET API maps EF entities to this table and does
-- NOT run EF migrations in production.
--
-- Conventions match the rest of the schema: BIGINT IDENTITY ids, timestamps as TEXT in
-- 'YYYY-MM-DD HH:MM:SS' UTC via now_text(), case-insensitive unique email via lower().

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    email         TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    created_at    TEXT NOT NULL DEFAULT now_text()
);

-- Case-insensitive unique email (matches the API's lower(email) lookup on login).
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_lower ON users (lower(email));
